package com.mycompany.chatapppart1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
// Attribution: org.json library used for storing structured messages to a JSON file
// Sourced from MVNRepository: https://mvnrepository.com/artifact/org.json/json
import org.json.JSONObject;

/**
 * Message class -- represents a single chat message in ChatApp.
 * Handles message creation, validation, hashing, and storage.
 */
public class Message {
    // Global static tracking lists (Parallel Data Structures)
    private static List<String> sentMessages = new ArrayList<>();
    private static List<String> disregardedMessages = new ArrayList<>();
    private static List<String> storedMessages = new ArrayList<>();
    private static List<String> messageHashes = new ArrayList<>();
    private static List<String> messageIDs = new ArrayList<>();
    private static List<String> recipientList = new ArrayList<>();
    

    // Bottom of Message.java
public static java.util.List<String> getSentMessages() {
    return sentMessages;
}

public static java.util.List<String> getDisregardedMessages() {
    return disregardedMessages;
}

public static java.util.List<String> getStoredMessages() {
    return storedMessages;
}

public static java.util.List<String> getMessageHashes() {
    return messageHashes;
}

public static java.util.List<String> getMessageIDs() {
    return messageIDs;
}

public static java.util.List<String> getRecipientList() {
    return recipientList;
}
    
    // Object Instance Attributes
    private String messageID;       // 10-digit randomly generated ID
    private int messageNumber;      // Position in the send loop counter
    private String recipient;        // Validated international cell number
    private String messageText;      // Content max 250 characters
    private String messageHash;      // Autogenerated tracking token
    
    private static int totalMessages = 0; // Cumulative tracker for returnTotalMessages()
    
    
    // =========================================================================
    // CORE CONSTRUCTORS
    // =========================================================================

    /**
     * Primary operational constructor utilized by Main application loops.
     */
    public Message(int messageNumber, String recipient, String messageText) {
        this.messageNumber = messageNumber;
        this.recipient = recipient;
        this.messageText = messageText;
        this.messageID = generateRandomID();
        this.messageHash = createMessageHash();
        
        // Populate parallel arrays automatically upon instantiation
        messageIDs.add(this.messageID);
        messageHashes.add(this.messageHash);
        recipientList.add(this.recipient);
        sentMessages.add(this.messageText);
        
        storedMessages.add(this.messageText);
        totalMessages++;
    }
    
    /**
     * Overloaded constructor providing custom IDs (Typically used for Unit Testing verification).
     */
    public Message(String messageID, int messageNumber, String recipient, String messageText) {
        this.messageID = messageID;
        this.messageNumber = messageNumber;
        this.recipient = recipient;
        this.messageText = messageText;
        this.messageHash = createMessageHash();
        
        messageIDs.add(this.messageID);
        messageHashes.add(this.messageHash);
        recipientList.add(this.recipient);
        sentMessages.add(this.messageText);
        
        storedMessages.add(this.messageText);
        totalMessages++;
    }

    // =========================================================================
    // UTILITY, SEARCH, & REPORTING METHODS
    // =========================================================================
    
    /**
     * Loops through sent messages and returns a formatted dashboard report.
     */
    /**
     * Formats and returns a report of all messages currently sitting in the storage cache.
     */
    public static String displayAllStoredMessages() {
        // Safety check: verify if the list contains records
        if (storedMessages == null || storedMessages.isEmpty()) {
            return "No stored messages available in the cache. Try loading from file first.";
        }

        StringBuilder report = new StringBuilder();
        report.append("\n==================================================\n");
        report.append("               ALL STORED MESSAGES                \n");
        report.append("==================================================\n");
        
        // Loop through the stored messages list
        for (int i = 0; i < storedMessages.size(); i++) {
            report.append(i + 1).append(". ").append(storedMessages.get(i)).append("\n");
            report.append("--------------------------------------------------\n");
        }
        
        return report.toString();
    }
    
    /**
     * Loops through storedMessages to find and return the longest text string.
     */
    public static String displayLongestMessage() {
        String longest = "";
        for (String currentMessage : storedMessages) {
            if (currentMessage != null && currentMessage.length() > longest.length()) {
                longest = currentMessage;
            }
        }
        return longest.isEmpty() ? "No stored messages available." : longest;
    }
    
    /**
     * Parallel Search: Finds matching ID and returns the corresponding message text.
     */
public static String searchByMessageID(String targetID) {
    // Safety check: handle empty or null input gracefully
    if (targetID == null || targetID.trim().isEmpty()) {
        return "Invalid search criteria. Please enter a valid ID.";
    }
    
    // Safety check: If nothing has been loaded into memory yet
    if (messageIDs == null || messageIDs.isEmpty()) {
        return "No messages currently loaded in system tracking memory.";
    }

    // Loop through your parallel array lists to match the ID
    for (int i = 0; i < messageIDs.size(); i++) {
        if (messageIDs.get(i) != null && messageIDs.get(i).equals(targetID)) {
            // Found a match! Construct a descriptive string return
            return "--- Message Found ---\n" +
                   "ID: " + messageIDs.get(i) + "\n" +
                   "Recipient: " + recipientList.get(i) + "\n" +
                   "Message: " + storedMessages.get(i) + "\n" +
                   "Hash: " + messageHashes.get(i) + "\n" +
                   "---------------------";
        }
    }
    
    return "Message ID \"" + targetID + "\" could not be found.";
}
    /**
     * Parallel Search: Collects and returns EVERY message sent to a specific recipient.
     */
public static String searchByRecipient(String recipient) {
    StringBuilder results = new StringBuilder();
    for (int i = 0; i < recipientList.size(); i++) {
        if (recipientList.get(i).equals(recipient)) {
            results.append(sentMessages.get(i)).append("\n");
        }
    }
    return results.toString();
}

    /**
     * Deletes a record out of all tracking arrays simultaneously to preserve indices.
     */
public static String deleteByHash(String targetHash) {
    if (targetHash == null || targetHash.trim().isEmpty()) {
        return "Invalid hash token provided.";
    }

    if (messageHashes == null || messageHashes.isEmpty()) {
        return "No messages are currently loaded in memory to delete.";
    }

    boolean foundAndDeleted = false;
    String deletedText = "";

    // 1. STEP ONE: Find and remove the item from RAM memory arrays ONLY
    for (int i = messageHashes.size() - 1; i >= 0; i--) {
        if (messageHashes.get(i) != null && messageHashes.get(i).equalsIgnoreCase(targetHash)) {
            
            deletedText = storedMessages.get(i); 
            
            // Remove from ALL parallel lists simultaneously
            messageHashes.remove(i);
            messageIDs.remove(i);
            recipientList.remove(i);
            storedMessages.remove(i); 
            sentMessages.remove(i); // Keep this mirrored too
            
            foundAndDeleted = true;
            break; // Stop looping immediately once we find our match!
        }
    }

    // 2. STEP TWO: Save the remaining data back to messages.json (OUTSIDE the loop!)
    if (foundAndDeleted) {
        try (java.io.FileWriter fw = new java.io.FileWriter("messages.json", false)) { // 'false' completely rewrites clean data
            java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
            java.io.PrintWriter out = new java.io.PrintWriter(bw);
            
            // Loop through the remaining active items left in memory
            for (int j = 0; j < storedMessages.size(); j++) {
                org.json.JSONObject json = new org.json.JSONObject();
                json.put("messageID", messageIDs.get(j));
                json.put("messageHash", messageHashes.get(j));
                json.put("recipient", recipientList.get(j));
                json.put("messageText", storedMessages.get(j)); 
                
                out.println(json.toString());
            }
        } catch (java.io.IOException e) {
            System.out.println("Error updating local storage file: " + e.getMessage());
        }
        
        return "Message: \"" + deletedText + "\" successfully deleted from storage.";
    }

    return "Message Hash not found.";
}


    /**
     * Generates a clean formatting report summary.
     */
    public static String printMessages() {
    StringBuilder report = new StringBuilder();
    report.append("=== Message Report ===\n");
    for (int i = 0; i < sentMessages.size(); i++) {
        report.append("Hash: ").append(messageHashes.get(i))
              .append(" | Recipient: ").append(recipientList.get(i))
              .append(" | Message: ").append(sentMessages.get(i))
              .append("\n");
    }
    return report.toString();
}
        

// Inside Message.java

// Attribution: org.json library - https://mvnrepository.com/artifact/org.json/json
public static void loadStoredMessages() {
    // Clear out lists to prevent duplicates on manual re-calls
    storedMessages.clear();
    messageIDs.clear();
    messageHashes.clear();
    recipientList.clear();
    
    java.io.File file = new java.io.File("messages.json");
    if (!file.exists()) return;

    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file))) {
        String line;
        // Inside Message.java -> loadStoredMessages()
       // Inside Message.java -> loadStoredMessages()
while ((line = br.readLine()) != null) {
    line = line.trim();
    if (!line.isEmpty()) {
        org.json.JSONObject jsonObject = new org.json.JSONObject(line);
        
        // Make sure ALL FOUR of these lines are here inside your startup loop!
        messageIDs.add(jsonObject.optString("messageID", ""));
        messageHashes.add(jsonObject.optString("messageHash", ""));
        recipientList.add(jsonObject.optString("recipient", ""));
        storedMessages.add(jsonObject.optString("messageText", "")); 
    }
}
    } catch (Exception e) {
        System.out.println("Error loading persistence streams: " + e.getMessage());
    }
}

    // =========================================================================
    // INTERNAL COMPONENT METHODS & VALIDATIONS
    // =========================================================================

    private String generateRandomID() {
        Random rand = new Random();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            sb.append(rand.nextInt(10));
        }
        return sb.toString();
    }

    public boolean checkMessageID() {
        return this.messageID != null && this.messageID.length() == 10;
    }

    public String checkMessageLength() {
        return checkMessageLength(this.messageText);
    }

    public String checkMessageLength(String message) {
        if (message == null) return "Message ready to send.";
        if (message.length() > 250) {
            int over = message.length() - 250;
            return "Message exceeds 250 characters by " + over + "; please reduce the size.";
        }
        return "Message ready to send.";
    }

    public String checkRecipientCell() {
        if (this.recipient != null && this.recipient.startsWith("+27") && this.recipient.length() == 12) {
            return "Cell phone number successfully captured.";
        }
        return "Cell phone number is incorrectly formatted or does not contain an international code. Please correct the number and try again.";
    }

    public String createMessageHash() {
        if (this.messageID == null || this.messageText == null || this.messageText.trim().isEmpty()) {
            return "";
        }
        String idPart = this.messageID.substring(0, 2);
        
        String[] words = this.messageText.trim().split("\\s+");
        String firstWord = words[0];
        String lastWord = words[words.length - 1];
        
        firstWord = firstWord.replaceAll("[^a-zA-Z0-9]", "");
        lastWord = lastWord.replaceAll("[^a-zA-Z0-9]", "");
        
        String hash = idPart + ":" + this.messageNumber + ":" + firstWord + lastWord;
        return hash.toUpperCase();
    }

  // Inside Message.java
public String sentMessage(int choice) {
    if (choice == 1) {
        // Option 1: Send Message logic...
        return "Message successfully sent.";
    } else if (choice == 2) {
        // Option 2: Discard Message logic...
        return "Press 0 to delete the message.";
    } else if (choice == 3) {
        try (java.io.FileWriter fw = new java.io.FileWriter("messages.json", true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
             java.io.PrintWriter out = new java.io.PrintWriter(bw)) {
            
            org.json.JSONObject json = new org.json.JSONObject();
            
            json.put("messageID", this.messageID); 
            json.put("messageHash", this.createMessageHash());
            
            // CORRECTION: Pass the raw string variable holding the actual cell number field
            // Replace "this.recipient" with whatever your class string field name is
            json.put("recipient", this.recipient); 
            
            json.put("messageText", this.messageText); 
            
            out.println(json.toString());
            return "Message successfully stored.";
            
        } catch (java.io.IOException e) {
            System.out.println("Error saving data: " + e.getMessage());
            return "Failed to store message.";
        }
    }
        return null;
}
    public void printSingleMessage() {
    System.out.println("Message ID: " + this.messageID);
    
    // CORRECTION: Call the method that calculates the hash instead of the empty variable
    System.out.println("Message Hash: " + this.createMessageHash());
    
    System.out.println("Recipient: " + this.recipient);
    System.out.println("Message: " + this.messageText);
}

    public void storeMessage() {
        JSONObject obj = new JSONObject();
        obj.put("messageID", this.messageID);
        obj.put("messageHash", this.messageHash);
        obj.put("recipient", this.recipient);
        obj.put("messageText", this.messageText);
        
        storedMessages.add(this.messageText);
        
        try (FileWriter fw = new FileWriter("messages.json", true)) {
            fw.write(obj.toString() + System.lineSeparator());
        } catch (IOException e) {
            System.out.println("Error saving JSON data: " + e.getMessage());
        }
    }

    public static int returnTotalMessages() {
        return totalMessages;
    }
}




