package com.mycompany.chatapppart1;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
// Attribution: org.json library used for storing structured messages to a JSON file
// Sourced from MVNRepository: https://mvnrepository.com/artifact/org.json/json
import org.json.JSONObject; 

/**
 * Message class -- represents a single chat message in ChatApp.
 * Handles message creation, validation, hashing, and storage.
 */
public class Message {

    private String messageID;       // 10-digit randomly generated ID
    private int messageNumber;      // Position in the send loop counter
    private String recipient;        // Validated international cell number
    private String messageText;      // Content max 250 characters
    private String messageHash;      // Autogenerated tracking token
    
    private static int totalMessages = 0; // Cumulative tracker for returnTotalMessages()

    /**
     * Standard constructor utilized throughout the main application loops
     */
    public Message(int messageNumber, String recipient, String messageText) {
        this.messageNumber = messageNumber;
        this.recipient = recipient;
        this.messageText = messageText;
        this.messageID = generateRandomID();
        this.messageHash = createMessageHash();
        totalMessages++;
    }

    /**
     * Overloaded test constructor providing a predictable ID to verify the hash format
     */
    public Message(String messageID, int messageNumber, String recipient, String messageText) {
        this.messageID = messageID;
        this.messageNumber = messageNumber;
        this.recipient = recipient;
        this.messageText = messageText;
        this.messageHash = createMessageHash();
        totalMessages++;
    }

    private String generateRandomID() {
        Random rand = new Random();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            sb.append(rand.nextInt(10));
        }
        return sb.toString();
    }

    /**
     * Returns true if the message ID exists and is exactly 10 characters long
     */
    public boolean checkMessageID() {
        return this.messageID != null && this.messageID.length() == 10;
    }

    /**
     * Standard validation checking instance variable text length
     */
    public String checkMessageLength() {
        return checkMessageLength(this.messageText);
    }

    /**
     * Javadoc Standard: Checks that the message text does not exceed 250 characters.
     * @param message the text entered by the user
     * @return success or failure String message
     */
    public String checkMessageLength(String message) {
        if (message == null) return "Message ready to send.";
        if (message.length() > 250) {
            int over = message.length() - 250;
            return "Message exceeds 250 characters by " + over + "; please reduce the size.";
        }
        return "Message ready to send.";
    }

    /**
     * Validates that the cell number has international components and structural boundaries
     */
    public String checkRecipientCell() {
        if (this.recipient != null && this.recipient.startsWith("+27") && this.recipient.length() == 12) {
            return "Cell phone number successfully captured.";
        }
        return "Cell phone number is incorrectly formatted or does not contain an international code. Please correct the number and try again.";
    }

    /**
     * Compiles a capitalized tracking hash according to formula specifications
     */
    public String createMessageHash() {
        if (this.messageID == null || this.messageText == null || this.messageText.trim().isEmpty()) {
            return "";
        }
        String idPart = this.messageID.substring(0, 2);
        
        // Split via space formatting boundaries
        String[] words = this.messageText.trim().split("\\s+");
        String firstWord = words[0];
        String lastWord = words[words.length - 1];
        
        // Remove trailing punctuation marks (?, ., !) to prevent hash text fragmentation
        firstWord = firstWord.replaceAll("[^a-zA-Z0-9]", "");
        lastWord = lastWord.replaceAll("[^a-zA-Z0-9]", "");
        
        String hash = idPart + ":" + this.messageNumber + ":" + firstWord + lastWord;
        return hash.toUpperCase();
    }

    /**
     * Resolves sub-menu selections and processes choices accordingly
     */
    public String sentMessage(int option) {
        switch (option) {
            case 1:
                return "Message successfully sent.";
            case 2:
                return "Press 0 to delete the message.";
            case 3:
                storeMessage();
                return "Message successfully stored.";
            default:
                return "";
        }
    }

    /**
     * Prints out structured parameters into correct execution sequencing positions
     */
    public void printMessages() {
        System.out.println("Message ID: " + this.messageID);
        System.out.println("Message Hash: " + this.messageHash);
        System.out.println("Recipient: " + this.recipient);
        System.out.println("Message: " + this.messageText);
    }

    /**
     * Saves information content to local disk file storage as JSON structures
     */
    public void storeMessage() {
        JSONObject obj = new JSONObject();
        obj.put("messageID", this.messageID);
        obj.put("recipient", this.recipient);
        obj.put("message", this.messageText);
        
        try (FileWriter fw = new FileWriter("messages.json", true)) {
            fw.write(obj.toString() + System.lineSeparator());
        } catch (IOException e) {
            System.out.println("Error saving JSON data: " + e.getMessage());
        }
    }

    /**
     * Static summary method returning cumulative metrics count
     */
    public static int returnTotalMessages() {
        return totalMessages;
    }
}