package com.mycompany.chatapppart1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
// Attribution: org.json library used for storing structured messages to a JSON file
// Sourced from MVNRepository: https://mvnrepository.com/artifact/org.json/json
import org.json.JSONObject;

/**
 * Message class -- represents a single chat message in ChatApp.
 * Handles message creation, validation, hashing, and storage.
 */
public class Message {
    // Global static tracking lists (Parallel Data Structures)
    private static List<String> sentMessages = new ArrayList<>();
    private static List<String> disregardedMessages = new ArrayList<>();
    private static List<String> storedMessages = new ArrayList<>();
    private static List<String> messageHashes = new ArrayList<>();
    private static List<String> messageIDs = new ArrayList<>();
    private static List<String> recipientList = new ArrayList<>();

    // Object Instance Attributes
    private String messageID;       // 10-digit randomly generated ID
    private int messageNumber;      // Position in the send loop counter
    private String recipient;        // Validated international cell number
    private String messageText;      // Content max 250 characters
    private String messageHash;      // Autogenerated tracking token
    
    private static int totalMessages = 0; // Cumulative tracker for returnTotalMessages()
    
    // =========================================================================
    // CORE CONSTRUCTORS
    // =========================================================================

    /**
     * Default No-Argument Constructor. Required for empty template initialization.
     */
    public Message() {
        this.messageID = generateRandomID();
        this.messageText = "";
        this.recipient = "";
        this.messageHash = "";
    }

    /**
     * Primary operational constructor utilized by Main application loops.
     */
    public Message(int messageNumber, String recipient, String messageText) {
        this.messageNumber = messageNumber;
        this.recipient = recipient;
        this.messageText = messageText;
        this.messageID = generateRandomID();
        this.messageHash = createMessageHash();
        
        // Populate parallel arrays automatically upon instantiation
        messageIDs.add(this.messageID);
        messageHashes.add(this.messageHash);
        recipientList.add(this.recipient);
        sentMessages.add(this.messageText);
        storedMessages.add(this.messageText);
        totalMessages++;
    }
    
    /**
     * Overloaded constructor providing custom IDs (Typically used for Unit Testing verification).
     */
    public Message(String messageID, int messageNumber, String recipient, String messageText) {
        this.messageID = messageID;
        this.messageNumber = messageNumber;
        this.recipient = recipient;
        this.messageText = messageText;
        this.messageHash = createMessageHash();
        
        messageIDs.add(this.messageID);
        messageHashes.add(this.messageHash);
        recipientList.add(this.recipient);
        sentMessages.add(this.messageText);
        storedMessages.add(this.messageText);
        totalMessages++;
    }

    // =========================================================================
    // GLOBAL STATIC GETTERS
    // =========================================================================

    public static List<String> getSentMessages() { return sentMessages; }
    public static List<String> getDisregardedMessages() { return disregardedMessages; }
    public static List<String> getStoredMessages() { return storedMessages; }
    public static List<String> getMessageHashes() { return messageHashes; }
    public static List<String> getMessageIDs() { return messageIDs; }
    public static List<String> getRecipientList() { return recipientList; }

    // =========================================================================
    // UTILITY, SEARCH, & REPORTING METHODS
    // =========================================================================
    
    /**
     * Formats and returns a report of all messages currently sitting in the storage cache.
     */
    public static String displayAllStoredMessages() {
        if (storedMessages == null || storedMessages.isEmpty()) {
            return "No stored messages available in the cache. Try loading from file first.";
        }

        StringBuilder report = new StringBuilder();
        report.append("\n==================================================\n");
        report.append("               ALL STORED MESSAGES                \n");
        report.append("==================================================\n");
        
        for (int i = 0; i < storedMessages.size(); i++) {
            report.append(i + 1).append(". ").append(storedMessages.get(i)).append("\n");
            report.append("--------------------------------------------------\n");
        }
        
        return report.toString();
    }
    
    /**
     * Loops through storedMessages to find and return the longest text string.
     */
    public static String displayLongestMessage() {
        String longest = "";
        for (String currentMessage : storedMessages) {
            if (currentMessage != null && currentMessage.length() > longest.length()) {
                longest = currentMessage;
            }
        }
        return longest.isEmpty() ? "No stored messages available." : longest;
    }
    
    /**
     * Parallel Search: Finds matching ID and returns the corresponding message text.
     */
    public static String searchByMessageID(String targetID) {
        if (targetID == null || targetID.trim().isEmpty()) {
            return "Invalid search criteria. Please enter a valid ID.";
        }
        
        if (messageIDs == null || messageIDs.isEmpty()) {
            return "No messages currently loaded in system tracking memory.";
        }

        for (int i = 0; i < messageIDs.size(); i++) {
            if (messageIDs.get(i) != null && messageIDs.get(i).equals(targetID)) {
                return "--- Message Found ---\n" +
                       "ID: " + messageIDs.get(i) + "\n" +
                       "Recipient: " + recipientList.get(i) + "\n" +
                       "Message: " + storedMessages.get(i) + "\n" +
                       "Hash: " + messageHashes.get(i) + "\n" +
                       "---------------------";
            }
        }
        
        return "Message ID \"" + targetID + "\" could not be found.";
    }

    /**
     * Parallel Search: Collects and returns EVERY message sent to a specific recipient.
     * FIXED: Keyed directly to iterate through recipientList to align perfectly with mock test environments.
     */
    public static String searchByRecipient(String recipient) {
        if (recipient == null || recipient.trim().isEmpty()) {
            return "No recipient provided.";
        }
        StringBuilder results = new StringBuilder();
        boolean found = false;
        
        for (int i = 0; i < recipientList.size(); i++) {
            if (recipientList.get(i) != null && recipientList.get(i).equals(recipient)) {
                // Safely grab text from whichever parallel array contains the generated items
                String msgText = "N/A";
                if (i < storedMessages.size()) {
                    msgText = storedMessages.get(i);
                } else if (i < sentMessages.size()) {
                    msgText = sentMessages.get(i);
                }
                
                results.append(msgText).append("\n");
                found = true;
            }
        }
        return found ? results.toString() : "No messages found for recipient: " + recipient;
    }

    /**
     * Deletes a record out of all tracking arrays simultaneously to preserve indices,
     * and forcefully syncs changes directly to messages.json.
     */
    public static String deleteByHash(String targetHash) {
        if (targetHash == null || targetHash.trim().isEmpty()) {
            return "Invalid hash token provided.";
        }

        if (messageHashes == null || messageHashes.isEmpty()) {
            return "No messages are currently loaded in memory to delete.";
        }

        boolean foundAndDeleted = false;
        String deletedText = "";

        // Loop backwards to safely remove records across multiple parallel arrays
        for (int i = messageHashes.size() - 1; i >= 0; i--) {
            if (messageHashes.get(i) != null && messageHashes.get(i).equalsIgnoreCase(targetHash.trim())) {
                if (i < storedMessages.size()) {
                    deletedText = storedMessages.get(i);
                    storedMessages.remove(i);
                }
                
                messageHashes.remove(i);
                if (i < messageIDs.size()) messageIDs.remove(i);
                if (i < recipientList.size()) recipientList.remove(i);
                if (i < sentMessages.size()) sentMessages.remove(i);
                
                foundAndDeleted = true;
                break; 
            }
        }

        // Force overwrite remaining items back to JSON data file
        if (foundAndDeleted) {
            File file = new File("messages.json");
            try (FileWriter fw = new FileWriter(file, false);
                 BufferedWriter bw = new BufferedWriter(fw)) { 
                
                for (int j = 0; j < storedMessages.size(); j++) {
                    JSONObject json = new JSONObject();
                    json.put("messageID", j < messageIDs.size() ? messageIDs.get(j) : "");
                    json.put("messageHash", j < messageHashes.size() ? messageHashes.get(j) : "");
                    json.put("recipient", j < recipientList.size() ? recipientList.get(j) : "");
                    json.put("messageText", storedMessages.get(j)); 
                    
                    bw.write(json.toString());
                    bw.newLine();
                }
                bw.flush(); 
            } catch (IOException e) {
                System.out.println("Error updating local storage file: " + e.getMessage());
            }
            
            return "Message: \"" + deletedText + "\" successfully deleted from storage.";
        }

        return "Message Hash not found.";
    }

    /**
     * Generates a clean formatting report summary.
     */
    public static String printMessages() {
        int max = Math.max(storedMessages.size(), Math.max(messageHashes.size(), sentMessages.size()));
        if (max == 0) {
            return "No messages sent or stored during this session.";
        }
        StringBuilder report = new StringBuilder();
        report.append("=== Message Report ===\n");
        for (int i = 0; i < max; i++) {
            String hash = (i < messageHashes.size()) ? messageHashes.get(i) : "N/A";
            String rec = (i < recipientList.size()) ? recipientList.get(i) : "N/A";
            String msg = (i < storedMessages.size()) ? storedMessages.get(i) : (i < sentMessages.size() ? sentMessages.get(i) : "N/A");
            
            report.append("Hash: ").append(hash)
                  .append(" | Recipient: ").append(rec)
                  .append(" | Message: ").append(msg)
                  .append("\n");
        }
        return report.toString();
    }
        
    /**
     * Sourced from persistence layers to read previous sessions back into RAM.
     */
    public static void loadStoredMessages() {
        storedMessages.clear();
        messageIDs.clear();
        messageHashes.clear();
        recipientList.clear();
        sentMessages.clear();
        
        File file = new File("messages.json");
        if (!file.exists()) return;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (!line.isEmpty()) {
                    JSONObject jsonObject = new JSONObject(line);
                    
                    String id = jsonObject.optString("messageID", "");
                    String hash = jsonObject.optString("messageHash", "");
                    String rec = jsonObject.optString("recipient", "");
                    String text = jsonObject.optString("messageText", "");
                    
                    messageIDs.add(id);
                    messageHashes.add(hash);
                    recipientList.add(rec);
                    storedMessages.add(text); 
                    sentMessages.add(text);
                }
            }
        } catch (Exception e) {
            System.out.println("Error loading persistence streams: " + e.getMessage());
        }
    }

    // =========================================================================
    // INTERNAL COMPONENT METHODS & VALIDATIONS
    // =========================================================================

    private String generateRandomID() {
        Random rand = new Random();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            sb.append(rand.nextInt(10));
        }
        return sb.toString();
    }

    public boolean checkMessageID() {
        return this.messageID != null && this.messageID.length() == 10;
    }

    public String checkMessageLength() {
        return checkMessageLength(this.messageText);
    }

    public String checkMessageLength(String message) {
        if (message == null || message.trim().isEmpty()) return "Message ready to send.";
        if (message.length() > 250) {
            int over = message.length() - 250;
            return "Message exceeds 250 characters by " + over + "; please reduce the size.";
        }
        return "Message ready to send.";
    }

    public String checkRecipientCell() {
        return checkRecipientCell(this.recipient);
    }

    public String checkRecipientCell(String recipientCell) {
        if (recipientCell != null && recipientCell.startsWith("+27") && recipientCell.length() == 12) {
            this.recipient = recipientCell; 
            return "Cell phone number successfully captured.";
        }
        return "Cell phone number is incorrectly formatted or does not contain an international code. Please correct the number and try again.";
    }

    public String createMessageHash() {
        if (this.messageID == null || this.messageText == null || this.messageText.trim().isEmpty()) {
            return "EMPTY_HASH";
        }
        String idPart = this.messageID.substring(0, 2);
        
        String[] words = this.messageText.trim().split("\\s+");
        String firstWord = words[0];
        String lastWord = words[words.length - 1];
        
        firstWord = firstWord.replaceAll("[^a-zA-Z0-9]", "");
        lastWord = lastWord.replaceAll("[^a-zA-Z0-9]", "");
        
        String hash = idPart + ":" + this.messageNumber + ":" + firstWord + lastWord;
        this.messageHash = hash.toUpperCase();
        return this.messageHash;
    }

    public String sentMessage() {
        storeMessage();
        return "Message Action Processed Successfully.";
    }

    public String sentMessage(int choice) {
        if (choice == 1) {
            return "Message successfully sent.";
        } else if (choice == 2) {
            return "Press 0 to delete the message.";
        } else if (choice == 3) {
            storeMessage();
            return "Message successfully stored.";
        }
        return "Invalid choice processed.";
    }

    public void printSingleMessage() {
        System.out.println("Message ID: " + this.messageID);
        System.out.println("Message Hash: " + this.createMessageHash());
        System.out.println("Recipient: " + this.recipient);
        System.out.println("Message: " + this.messageText);
    }

    /**
     * Saves active objects and synchronizes RAM tracking lists smoothly.
     */
    public void storeMessage() {
        if (this.messageHash == null || this.messageHash.equals("EMPTY_HASH") || this.messageHash.isEmpty()) {
            this.messageHash = createMessageHash();
        }
        
        JSONObject obj = new JSONObject();
        obj.put("messageID", this.messageID);
        obj.put("messageHash", this.messageHash);
        obj.put("recipient", this.recipient);
        obj.put("messageText", this.messageText != null ? this.messageText : "");
        
        File file = new File("messages.json");
        try (FileWriter fw = new FileWriter(file, true);
             BufferedWriter bw = new BufferedWriter(fw)) {
            bw.write(obj.toString());
            bw.newLine();
            bw.flush(); 
        } catch (IOException e) {
            System.out.println("Error saving JSON data: " + e.getMessage());
        }
    }

    public static int returnTotalMessages() {
        return totalMessages;
    }

    public String getMessageID() {
        return this.messageID;
    }
}